main_controllers:
  resource:  '../src/Controller/'
  type: attribute
  prefix: '/twig'

react_controllers:
  resource: ../src/Controller/React/
  type: attribute
  prefix: '/'

my_profile:
  path: /api/profile/me
  methods: [ 'GET' ]
  defaults:
    _controller: App\Controller\Api\ProfileController::me
